name: Build and Release

on:
  push:
    tags:
      - '*-v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      - name: Extract tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set output filename
        id: vars
        run: |
          if [ "${{ matrix.os }}" = "windows" ]; then
          echo "FILENAME=noclonpack.exe" >> $GITHUB_ENV
          else
          echo "FILENAME=noclonpack" >> $GITHUB_ENV
          fi

      - name: Build
        run: |
          mkdir -p build/${{ matrix.os }}_${{ matrix.arch }}
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -ldflags "-X main.Version=${TAG_NAME}" -o build/${{ matrix.os }}_${{ matrix.arch }}/${FILENAME}
          ls -R build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: noclonpack-${{ matrix.os }}-${{ matrix.arch }}
          path: build/${{ matrix.os }}_${{ matrix.arch }}/*

      - name: Archive Production Build
        run: |
          tar -czf ${{github.ref_name}}.tar.gz ./build

      - name: Create Release
        run: |
          snapshot_or_relealse=`echo ${{github.ref_name}} | cut -d '-' -f1`
          version=`echo ${{githu.ref_name}} | cut -d '-' -f2`
          if [ ${snapshot_or_relealse} = "snapshot" ]; then
          gh release create ${version} --prerelease --generate-notes ${{github.ref_name}}.tar.gz
          else
          gh release create ${version} --latest --generate-notes ${{github.ref_name}}.tar.gz
          fi
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
