name: Build and Release

on:
  push:
    tags:
      - '*-v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      - name: Extract tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set output filename
        id: vars
        run: |
          if [ "${{ matrix.os }}" = "windows" ]; then
          echo "FILENAME=noclonpack.exe" >> $GITHUB_ENV
          else
          echo "FILENAME=noclonpack" >> $GITHUB_ENV
          fi

      - name: Build
        run: |
          mkdir -p build/${{ matrix.os }}_${{ matrix.arch }}
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -ldflags "-X main.Version=${TAG_NAME}" -o build/${{ matrix.os }}_${{ matrix.arch }}/${FILENAME}
          ls -R build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: noclonpack-${{ matrix.os }}-${{ matrix.arch }}
          path: build/${{ matrix.os }}_${{ matrix.arch }}/*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: download
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        run: |
          ls -R
          snapshot_or_relealse=`echo ${{github.ref_name}} | cut -d '-' -f1`
          version=`echo ${{github.ref_name}} | cut -d '-' -f2`
          files=$(find artifacts -type f) # Find only files in the artifacts directory
          if [ ${snapshot_or_relealse} = "snapshot" ]; then
            gh release create ${version} --target ${{github.sha}} --prerelease --generate-notes $files
          else
            gh release create ${version} --target ${{github.sha}} --latest --generate-notes $files
          fi
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
